# Generated by Django 3.0.7 on 2020-06-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200616_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='discription',
            new_name='description',
        ),
    ]
